name: annalog
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=2.4.2
  - pandas=3.0.1
  - tqdm=4.67.3
  - pytorch=2.10.0
  - torchvision=0.25.0
  - rdkit=2025.09.6
  - scikit-learn=1.8.0
  - pip
  - pip:
      - chembl-gen-check==0.1.3
